# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install the required packages
RUN pip install --no-cache-dir -r requirements.txt

# Set the environment variable for data directory
ENV DATA_DIR /app/data/

# Set the environment variable for model directory
ENV MODEL_DIR /app/models/

# Set the entry point to run data_extraction.py script
ENTRYPOINT ["python", "scripts/data_extraction.py"]