tasks:
  - source: scripts/data_extraction.py
    product:
      nb: notebooks/ploomber-output/data_extraction.ipynb
      data: data/ploomber-output/1995_2022_vehicle_fuel_consumption.csv
      data: data/ploomber-output/Battery-electric_vehicles_2012-2022_(2022-05-16).csv
      data: data/ploomber-output/fuel_sold_motor_vehicles.csv
      data: data/ploomber-output/long_format_car_sales.csv
      data: data/ploomber-output/near_zero_vehicle_registrations.csv
      data: data/ploomber-output/Plug-in_hybrid_electric_vehicles_2012-2022_(2022-03-28).csv
      data: data/ploomber-output/vehicle_registrations_type_vehicle.csv
      data: data/ploomber-output/wide_format_car_sales.csv
  - source: scripts/car_score_modelling.py
    product:
      nb: notebooks/ploomber-output/car_score_modelling.ipynb
      data: models/hard_voting_classifier_co2_fuel.pkl
  - source: scripts/predict_scores.py
    product:
      nb: notebooks/ploomber-output/predict_scores.ipynb
      data: data/ploomber-output/predicted_co2_rating.csv